name: build sdist

on:
  pull_request:
  workflow_call:
  workflow_dispatch:

env:
  POETRY_VERSION: 1.8

jobs:
  build-sdist:
    name: Build source distribution
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: python

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: 3.12

      - name: Install poetry
        run: |
          python -m pip install --upgrade pip
          python -m pip install poetry==${{env.POETRY_VERSION}}

      - name: Configure poetry
        shell: bash
        run: poetry config virtualenvs.in-project true --directory python

      - name: Install dependencies
        run: poetry install --no-interaction --no-root --without=dev --directory python

      - name: Install project
        run: poetry install --no-interaction --without=dev --directory python

      - name: Build package
        run: poetry build --format=sdist --directory python

      - name: Upload sdist
        uses: actions/upload-artifact@v4
        with:
          name: tp53-sdist
          path: python/dist/*.tar.gz
          if-no-files-found: error
