name: build wheels

on:
  pull_request:
  workflow_call:
  workflow_dispatch:

jobs:
  build-wheels:
    name: Build wheels for ${{ matrix.PYTHON_VERSION }}
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: python
    strategy:
      matrix:
        PYTHON_VERSION: ["3.11", "3.12", "3.13"]

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python ${{ matrix.PYTHON_VERSION }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.PYTHON_VERSION }}

      - name: Build wheels
        run: pip wheel --no-deps -w /tmp/wheelhouse .

      - name: Upload wheels
        uses: actions/upload-artifact@v4
        with:
          name: tp53-wheels-${{ matrix.PYTHON_VERSION }}
          path: /tmp/wheelhouse/tp53*.whl
          if-no-files-found: error
