name: publish tp53

on:
  push:
    tags: '\d+.\d+.\d+'

env:
  POETRY_VERSION: 1.8.2

jobs:
  on-main-branch-check:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: python
    outputs:
      on_main: ${{ steps.contains_tag.outputs.retval }}
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - uses: rickstaa/action-contains-tag@v1
        id: contains_tag
        with:
          reference: "main"
          tag: "${{ github.ref_name }}"

  python-tests:
    name: python-tests
    needs: on-main-branch-check
    if: ${{ needs.on-main-branch-check.outputs.on_main == 'true' }}
    uses: "./.github/workflows/tests_python.yml"

  scala-tests:
    name: scala-tests
    needs: on-main-branch-check
    if: ${{ needs.on-main-branch-check.outputs.on_main == 'true' }}
    uses: "./.github/workflows/tests_scala.yml"

  build-wheels:
    name: build wheels
    needs: python-tests
    uses: "./.github/workflows/build_wheels.yml"

  build-sdist:
    name: build source distribution
    needs: python-tests
    uses: "./.github/workflows/build_sdist.yml"

  publish-to-pypi:
    runs-on: ubuntu-latest
    needs: [build-wheels, build-sdist]
    environment: pypi
    permissions:
      id-token: write
    steps:
      - uses: actions/download-artifact@v4
        with:
          path: packages
          pattern: 'tp53-*'
          merge-multiple: true

      - uses: pypa/gh-action-pypi-publish@release/v1
        with:
          packages-dir: packages/
          skip-existing: true
          verbose: true

  build-seshat-exe:
    name: build seshat executable
    needs: scala-tests
    uses: "./.github/workflows/buil_seshat_exe.yml"

  make-changelog:
    runs-on: ubuntu-latest
    needs: publish-to-pypi
    outputs:
      release_body: ${{ steps.git-cliff.outputs.content }}
    steps:
      - name: Checkout the Repository at the Tagged Commit
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          ref: ${{ github.ref_name }}

      - name: Generate a Changelog
        uses: orhun/git-cliff-action@v3
        id: git-cliff
        with:
          config: ./python/pyproject.toml
          args: --latest --verbose
        env:
          GITHUB_REPO: ${{ github.repository }}

  make-github-release:
    runs-on: ubuntu-latest
    environment: github
    permissions:
      contents: write
      pull-requests: read
    needs: [build-seshat-exe, make-changelog]
    steps:
      - uses: actions/download-artifact@v4
        with:
          pattern: "seshat"
          merge-multiple: true
  
      - name: Create Draft Release
        id: create_release
        uses: softprops/action-gh-release@v2
        with:
          name: ${{ github.ref_name }}
          body: ${{ needs.make-changelog.outputs.release_body }}
          draft: false
          prerelease: false
          files: "seshat"
